[package]
name = "file-hasher-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
rfd = "0.10.0"
md5 = "0.7.0"
sha1_smol = "1.0.0"
sha256 = "1.0.3"